version: "3"

services:
  homeserver:
    image: matrixconduit/matrix-conduit:latest
    restart: unless-stopped
    ports:
      - 6167:6167
    volumes:
      - db:/var/lib/matrix-conduit/
    environment:
      CONDUIT_SERVER_NAME: matrix.conduit.local
      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
      CONDUIT_DATABASE_BACKEND: rocksdb
      CONDUIT_PORT: 6167
      CONDUIT_MAX_REQUEST_SIZE: 100_000_000
      CONDUIT_ALLOW_REGISTRATION: "true"
      CONDUIT_ALLOW_FEDERATION: "false"
      CONDUIT_ALLOW_CHECK_FOR_UPDATES: "false"
      CONDUIT_TRUSTED_SERVERS: "[]"
      CONDUIT_ADDRESS: 0.0.0.0

volumes:
  db:
